server:
  port: 8080
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres

spring:
  datasource:
    url: none

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration



